#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate ALL manuscript graphics and the complete numerical output of the
flux-tube note (rev4) with one command:

    python3 make_all.py

Produces, in the current directory:
    Fig1.pdf                 field profile E_par ~ J0 (field-weighted, as in
                             Eq. (wdef) of the manuscript) + Lambda=0,1,2
                             transverse mode energies
    Fig3.pdf                 d_break(m_pi) curve (Supplementary Fig. S1;
                             file name Fig3.pdf) with the published lattice
                             string-breaking values (simulated-ensemble
                             points only, plus the physical-point
                             extrapolation)
    Fig2.pdf                 main-text Fig. 2: the parameter-eliminated
                             product P against its
                             model value P0 = 2.6707: two cross-study
                             instantiations and the sharpest (B2-conditional)
                             mixed one
    GraphicalAbstract.png    480 x 262 px (11:6), illustrative only, no
                             result numbers -- per EPJ Plus guidelines
    GraphicalAbstract.pdf    vector twin of the same graphic (for records)
    numerical_results.txt    every number quoted in the manuscript text and
                             in the manuscript tables (Tables 1-2 and
                             Supplementary Table S1), from
                             width_numbers.compute()

All derived quantities entering the central analysis are generated by
width_numbers.py (single source of truth), including the physical constant
hbar*c and the GMOR parameter B_GMOR imported below; the only literature
inputs hard-coded in this driver are the published lattice string-breaking
points plotted in Supplementary Fig. S1 (file Fig3.pdf), quoted verbatim in
the manuscript text.

Requires: mpmath, numpy, scipy, matplotlib.
"""
import io
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from scipy.special import j0

from width_numbers import compute, report, HB as _HB, B_GMOR as _B_GMOR

plt.rcParams.update({
    'font.family': 'serif',
    'mathtext.fontset': 'dejavuserif',
    'axes.linewidth': 0.8,
    'font.size': 9,
    'pdf.fonttype': 42,
})

R = compute()
HBARC = float(_HB)                         # GeV fm, from width_numbers.py
B_GMOR = float(_B_GMOR)                    # GeV, from width_numbers.py
R0 = float(R['R0'])
X01, X11, X21 = float(R['x01']), float(R['x11']), float(R['x21'])
WR0 = float(R['wR0'])                      # rms radius / R0 = 0.5553


# ---------------------------------------------------------- numerical output
def write_numbers(path='numerical_results.txt'):
    buf = io.StringIO()
    report(R, out=lambda s='': buf.write(str(s) + '\n'))
    with open(path, 'w') as fh:
        fh.write(buf.getvalue())
    print('wrote %s' % path)


# --------------------------------------------------------------- Figure 1 ---
def figure1(path='Fig1.pdf'):
    """(a) FIELD profile E_par ~ J0 (linear weight, exactly the observable of
    Eq. (wdef)); dashed circle = field-weighted rms radius 0.5553 R0.
    (b) transverse mode energies for Lambda = 0,1,2 (no parity/C labels)."""
    fig = plt.figure(figsize=(9.6, 3.2))
    gs = fig.add_gridspec(1, 3, width_ratios=[1.10, 0.05, 1.05], wspace=0.75)

    ax = fig.add_subplot(gs[0, 0])
    n = 600
    lim = R0 * 1.18
    xs = np.linspace(-lim, lim, n)
    X, Y = np.meshgrid(xs, xs)
    Rr = np.hypot(X, Y)
    Z = np.where(Rr <= R0, j0(X01 * Rr / R0), np.nan)     # FIELD, not squared
    im = ax.imshow(Z, origin='lower', extent=[-lim, lim, -lim, lim],
                   cmap='Blues', vmin=0.0, vmax=1.0, interpolation='bilinear')
    ax.add_patch(plt.Circle((0, 0), R0, fill=False, color='black', lw=1.4))
    ax.add_patch(plt.Circle((0, 0), WR0 * R0, fill=False, color='#b03060',
                            lw=1.2, ls='--'))
    ax.set_aspect('equal')
    ax.axis('off')
    ax.text(0, -R0 * 1.30, r'$R_0 = 0.81$ fm', ha='center', va='top',
            fontsize=10)
    ax.text(WR0 * R0 * 0.72, WR0 * R0 * 0.80,
            r'$\sqrt{\langle r_\perp^2\rangle}$', color='#b03060', fontsize=9)
    ax.text(-lim, lim * 0.98, '(a)', ha='left', va='top', fontsize=11,
            fontweight='bold')

    cax = fig.add_subplot(gs[0, 1])
    cb = fig.colorbar(im, cax=cax)
    cb.set_ticks([0.0, 0.5, 1.0])
    cb.ax.yaxis.set_label_position('left')
    cb.ax.yaxis.set_ticks_position('left')
    cb.ax.set_ylabel(r'$E_\parallel\propto J_0(x_{0,1}r/R_0)$',
                     fontsize=8, labelpad=4)
    cb.ax.tick_params(labelsize=8)
    cb.outline.set_linewidth(0.6)

    ax2 = fig.add_subplot(gs[0, 2])
    levels = [(X01, r'$\Sigma$-type $(\Lambda{=}0)$', '#1f4e9c'),
              (X11, r'$\Pi$-type $(\Lambda{=}1)$', '#2ca05a'),
              (X21, r'$\Delta$-type $(\Lambda{=}2)$', '#b03060')]
    for x, lab, col in levels:
        e = x * HBARC / R0
        ax2.hlines(e, 0.06, 0.55, color=col, lw=2.4)
        ax2.text(0.60, e, '%s: %.2f GeV' % (lab, e), color=col,
                 va='center', ha='left', fontsize=9)
    ax2.set_xlim(0, 1.65)
    ax2.set_ylim(0.4, 1.4)
    ax2.set_xticks([])
    ax2.set_ylabel(r'transverse mode energy $x_{\Lambda,1}\hbar c/R_0$ [GeV]')
    ax2.text(0.02, 1.38, '(b)', ha='left', va='top', fontsize=11,
             fontweight='bold')
    for side in ('top', 'right'):
        ax2.spines[side].set_visible(False)

    fig.savefig(path, bbox_inches='tight')
    plt.close(fig)
    print('wrote %s   (levels: %.5f, %.5f, %.5f GeV; rms/R0 = %.5f)'
          % (path, X01 * HBARC / R0, X11 * HBARC / R0, X21 * HBARC / R0, WR0))


# --------------------------- Supplementary Fig. S1 (file Fig3.pdf) ---------
def figure2(path='Fig3.pdf'):
    """Supplementary Fig. S1 (file Fig3.pdf): d_break(m_pi) from
    Eq. (dbreak) with the published lattice values quoted verbatim in the
    manuscript text (no digitisation from rasters); these plotted literature
    points are the only quantitative inputs hard-coded in this driver."""
    def dbreak(mpi_gev, sigma):
        mq = mpi_gev**2 / (2.0 * B_GMOR)
        return 2.0 / sigma * np.sqrt(mq**2 + (X01 * HBARC / R0)**2) * HBARC

    sigma_pi = float(R['sigma_pi'])
    sigma_lo = 0.19                       # GeV^2, lattice band edge
    mpi = np.linspace(0.0, 0.80, 400)

    fig, ax = plt.subplots(figsize=(6.6, 4.2))
    ax.fill_between(mpi * 1e3, dbreak(mpi, sigma_pi), dbreak(mpi, sigma_lo),
                    color='#1f4e9c', alpha=0.12, lw=0,
                    label=r'band: $\sigma$ between $0.186$ and $0.190$ GeV$^2$')
    lo = mpi <= 0.30
    ax.plot(mpi[lo] * 1e3, dbreak(mpi[lo], sigma_pi), color='#1f4e9c', lw=2.0,
            label=r'model, $\sigma=\pi/R_0^2$')
    ax.plot(mpi[~lo] * 1e3, dbreak(mpi[~lo], sigma_pi), color='#1f4e9c',
            lw=2.0, ls=(0, (4, 3)))
    ax.axhline(float(R['d_break_pi']), color='0.35', lw=1.1, ls=':',
               label=r'chiral plateau $1.24$ fm')
    # published values quoted in the manuscript text
    ax.errorbar([135], [1.211], yerr=[0.013], fmt='D', ms=7, color='#2ca05a',
                mec='white', mew=0.8, capsize=2, zorder=6,
                label='physical-point extrapolation, Bulava et al. 2024')
    ax.plot([280], [1.22], marker='o', ms=6, color='#c07a1e', mec='white',
            mew=0.8, zorder=6, label=r'$m_\pi=280$ MeV, Bulava et al. 2019')
    ax.plot([640], [1.25], marker='s', ms=6, color='#7a4fa3', mec='white',
            mew=0.8, zorder=6, label=r'$m_\pi\simeq640$ MeV, Bali et al. 2005')
    ax.plot([135], [1.34], marker='D', ms=6, mfc='none', mec='#2ca05a',
            zorder=5)
    ax.plot([280], [1.29], marker='o', ms=6, mfc='none', mec='#c07a1e',
            zorder=5)
    ax.plot([], [], marker='o', ms=6, mfc='none', mec='0.35', ls='none',
            label='open: static-strange, for orientation')

    ax.set_xlabel(r'$m_\pi$ [MeV]')
    ax.set_ylabel(r'$d_{\rm break}$ [fm]')
    ax.set_xlim(0, 800)
    ax.set_ylim(0.95, 1.75)
    ax.legend(loc='upper left', frameon=True, framealpha=0.95, fontsize=7.2)
    ax.grid(alpha=0.18, lw=0.6)
    for side in ('top', 'right'):
        ax.spines[side].set_visible(False)
    fig.savefig(path, bbox_inches='tight')
    plt.close(fig)
    print('wrote %s  (plateau %.5f fm)' % (path, float(R['d_break_pi'])))


# ------------------------------------------------- main-text Figure 2 ------
def figure3(path='Fig2.pdf'):
    """Direct confrontation of the parameter-eliminated product P with its
    model value P0 = 2 sqrt(x01^2-4): two cross-study instantiations and the
    sharpest, B2-conditional mixed one."""
    P0 = float(R['P0'])
    rows = [
        (3, float(R['P_qcd']), float(R['dP_qcd_cons']), '#c07a1e', 'o', True,
         r'$N_f{=}2{+}1$ breaking $\times$ $N_f{=}2{+}1$ width'
         '\n' r'(cross-study; shared $\sigma t_0$ coherent)'),
        (2, float(R['P_baker']), float(R['dP_baker']), '#7a4fa3', 's', True,
         r'$N_f{=}2{+}1$ breaking $\times$ near-physical-mass width'
         '\n(robustness; intra-study correlations unknown)'),
        (1, float(R['prod_lat']), float(R['dprod_lat']), '#2ca05a', 'D', False,
         r'$N_f{=}2{+}1$ breaking $\times$ quenched width'
         '\n(sharpest; quenched-width proxy B2)'),
    ]
    fig, ax = plt.subplots(figsize=(6.6, 3.4))
    ax.axvline(P0, color='#1f4e9c', lw=2.0, zorder=2)
    ax.text(P0, 3.62, r'$P_0=2\sqrt{x_{0,1}^2-4}=2.671$', color='#1f4e9c',
            ha='center', va='bottom', fontsize=9)
    for yv, p, dp, col, mk, open_sym, lab in rows:
        ax.errorbar([p], [yv], xerr=[dp], fmt=mk, ms=7, color=col,
                    mfc='none' if open_sym else col,
                    mec=col if open_sym else 'white',
                    mew=1.4 if open_sym else 0.9,
                    capsize=3, elinewidth=1.6, zorder=4)
        ax.text(2.245, yv, lab, ha='left', va='center', fontsize=8)
        ax.text(p, yv - 0.26, r'$%.2f\pm%.2f$' % (p, dp), ha='center',
                va='top', fontsize=8, color=col)
    ax.set_xlim(2.22, 3.22)
    ax.set_ylim(0.35, 3.75)
    ax.set_yticks([])
    ax.set_xlabel(r'$P=(d_{\rm break}\sqrt{\sigma})\,'
                  r'\sqrt{\langle r_\perp^2\rangle\sigma}$')
    for side in ('top', 'right', 'left'):
        ax.spines[side].set_visible(False)
    ax.grid(axis='x', alpha=0.18, lw=0.6)
    fig.savefig(path, bbox_inches='tight')
    plt.close(fig)
    print('wrote %s  (P0=%.5f; points: %.3f(%.0f), %.3f(%.0f), %.3f(%.0f))'
          % (path, P0, rows[0][1], 1e3 * rows[0][2], rows[1][1],
             1e3 * rows[1][2], rows[2][1], 1e3 * rows[2][2]))


# ----------------------------------------------------- Graphical Abstract ---
def graphical_abstract(png='GraphicalAbstract.png',
                       pdf='GraphicalAbstract.pdf'):
    """EPJ Plus compliant: 480 px wide, 11:6 aspect (480 x 262 px),
    illustrative summary WITHOUT specific result numbers."""
    W, H = 4.80, 2.62                        # inches; x100 dpi = 480 x 262 px
    fig = plt.figure(figsize=(W, H))
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10 * H / W)
    ax.axis('off')
    ymax = 10 * H / W

    # cylinder with J0 shading (left)
    x0, x1, yc, ry = 0.55, 3.55, ymax * 0.56, 0.95
    yy = np.linspace(yc - ry, yc + ry, 220)
    xx = np.linspace(x0, x1, 160)
    XX, YY = np.meshgrid(xx, yy)
    ZZ = j0(X01 * np.abs(YY - yc) / ry)
    ax.imshow(ZZ, extent=[x0, x1, yc - ry, yc + ry], origin='lower',
              cmap='Blues', vmin=0, vmax=1, aspect='auto', zorder=1)
    th = np.linspace(0, 2 * np.pi, 100)
    for xe in (x0, x1):
        ax.plot(xe + 0.16 * np.cos(th), yc + ry * np.sin(th), color='#1f4e9c',
                lw=1.2, zorder=3)
    ax.plot([x0, x1], [yc + ry, yc + ry], color='#1f4e9c', lw=1.2, zorder=3)
    ax.plot([x0, x1], [yc - ry, yc - ry], color='#1f4e9c', lw=1.2, zorder=3)
    for xq, s in ((x0 - 0.05, r'$q$'), (x1 + 0.05, r'$\bar q$')):
        ax.plot([xq], [yc], marker='o', ms=6, color='#b03060', zorder=4)
        ax.text(xq, yc + ry + 0.28, s, ha='center', fontsize=9,
                color='#b03060')
    ax.annotate('', xy=(x0 + 0.55, yc + ry), xytext=(x0 + 0.55, yc),
                arrowprops=dict(arrowstyle='<->', lw=0.9, color='k'))
    ax.text(x0 + 0.72, yc + ry / 2, r'$R_0$', fontsize=10, va='center')
    ax.text((x0 + x1) / 2, yc - ry - 0.42,
            'one transverse scale,\nscalar Dirichlet mode $J_0$',
            ha='center', va='top', fontsize=7.6)

    # closure (middle)
    ax.text(5.15, yc + 0.55, r'$\sigma = c/R_0^{2}$', fontsize=12,
            ha='center')
    ax.text(5.15, yc - 0.10, 'one dimensionless\nparameter $c$',
            fontsize=7.6, ha='center', va='top')

    # two observables (right), calibrate -> predict
    bx = dict(boxstyle='round,pad=0.32', fc='#fdf3e3', ec='#c07a1e', lw=1.0)
    by = dict(boxstyle='round,pad=0.32', fc='#eef5ee', ec='#3a6b3a', lw=1.0)
    ax.text(8.32, yc + 1.05, r'string breaking  $d_{\rm break}\sqrt{\sigma}$',
            fontsize=8, ha='center', va='center', bbox=bx)
    ax.text(8.32, yc - 1.05, r'transverse width  '
            r'$\sqrt{\langle r_\perp^{2}\rangle\,\sigma}$',
            fontsize=8, ha='center', va='center', bbox=by)
    ax.annotate('', xy=(6.95, yc + 1.00), xytext=(5.90, yc + 0.35),
                arrowprops=dict(arrowstyle='<-', lw=1.2, color='#c07a1e'))
    ax.annotate('', xy=(6.95, yc - 1.00), xytext=(5.90, yc - 0.35),
                arrowprops=dict(arrowstyle='->', lw=1.2, color='#3a6b3a'))
    ax.text(6.10, yc + 0.98, 'calibrate', fontsize=7.2, color='#c07a1e',
            rotation=22, ha='left')
    ax.text(6.10, yc - 1.28, 'predict', fontsize=7.2, color='#3a6b3a',
            rotation=-22, ha='left')
    ax.text(5.0, 0.30, r'one lattice observable calibrates $c$ '
            u'\u2014 a second, physically distinct one tests it',
            fontsize=8.4, ha='center', style='italic')

    fig.savefig(png, dpi=100)
    fig.savefig(pdf)
    plt.close(fig)
    from PIL import Image
    with Image.open(png) as im:
        print('wrote %s (%d x %d px, aspect %.3f) and %s'
              % (png, im.width, im.height, im.width / im.height, pdf))


if __name__ == '__main__':
    write_numbers()
    figure1()
    figure2()
    figure3()
    graphical_abstract()
    print('done: Fig1, Fig2, Fig3 (= Supplementary Fig. S1), '
          'GraphicalAbstract, numerical_results.txt')
